apiVersion: v1
kind: Secret
metadata:
  name: quality-dashboard-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  users.htpasswd: |
    admin:$2y$05$QXbmXnVOT9dArRRMKMihteLuifETwdOmEg9g.YdaVMdlqtxh7YcOC
    test-user:$2y$05$Svrn.wYBBl7LvW7OJM0qFeyw4cqW1RTgs15Ttsd8J1G1nGT4yA9fm
